export type Cargo = "administrador" | "dentista" | "recepcionista";

export const permissoesPorCargo: Record<Cargo, Set<string>> = {
  administrador: new Set([
    "dashboard.ver",
    "pacientes.ver",
    "pacientes.criar",
    "pacientes.editar",
    "pacientes.excluir",
    "prontuario.ver",
    "prontuario.editar",
    "profissionais.ver",
    "profissionais.criar",
    "profissionais.editar",
    "profissionais.excluir",
    "procedimentos.ver",
    "procedimentos.criar",
    "procedimentos.editar",
    "procedimentos.excluir",
    "convenios.ver",
    "convenios.criar",
    "convenios.editar",
    "convenios.excluir",
    "agenda.ver",
    "agenda.criar",
    "agenda.editar",
    "agenda.excluir",
    "agenda.atender",
    "salas.gerenciar",
    "financeiro.ver",
    "financeiro.criar",
    "financeiro.baixar",
    "financeiro.excluir",
    "financeiro.comissoes",
    "financeiro.caixa",
    "config.ver",
    "config.editar",
    "mensagens.configurar",
    "usuarios.gerenciar",
  ]),
  dentista: new Set([
    "dashboard.ver",
    "pacientes.ver",
    "pacientes.editar",
    "prontuario.ver",
    "prontuario.editar",
    "profissionais.ver",
    "procedimentos.ver",
    "convenios.ver",
    "agenda.ver",
    "agenda.criar",
    "agenda.editar",
    "agenda.atender",
    "financeiro.ver",
  ]),
  recepcionista: new Set([
    "dashboard.ver",
    "pacientes.ver",
    "pacientes.criar",
    "pacientes.editar",
    "profissionais.ver",
    "procedimentos.ver",
    "convenios.ver",
    "agenda.ver",
    "agenda.criar",
    "agenda.editar",
    "agenda.atender",
    "financeiro.ver",
    "financeiro.criar",
    "financeiro.baixar",
  ]),
};

export function temPermissao(cargo: Cargo, permissao: string): boolean {
  return permissoesPorCargo[cargo]?.has(permissao) ?? false;
}
